### ISSUE TITLE
Error after upgrade to HomeAssistant 2025.6

### ISSUE THREAD

**Issue by shivan** [KoljaWindeler/kaco#18]
Integration is no more working after update to 2025.6.0

## Version of the custom_component
installed version:
7851ecb 

## Configuration

```yaml



```

## Describe the bug
Integration is no more working after update to 2025.6.0


## Debug log


```text

2025-06-13 22:22:57.514 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Kaco for kaco                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                     
File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/config_entries.py", line 749, in __async_setup_with_context                                                                                                                                                                                                                        
result = await component.async_setup_entry(hass, self)                                                                                                                                                                                                                                                                                                         
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                              
File "/home/homeassistant/.homeassistant/custom_components/kaco/__init__.py", line 35, in async_setup_entry                                                                                                                                                                                                                                             
await hass.config_entries.async_forward_entry_setup(config_entry, PLATFORM)                                                                                                                                                                                                                                                                                 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                               
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?       


```

**Comment by browi2618** [comment]
Same Problem here...Really hope it will be fixed soon :) Thanks !!!!!

**Comment by KoljaWindeler** [comment]
Please update and let me know if the fix  worked 
Thanks to https://github.com/KoljaWindeler/kaco/pull/17

**Comment by browi2618** [comment]
> Please update and let me know if the fix worked Thanks to [#17](https://github.com/KoljaWindeler/kaco/pull/17)

Thank a lot Kolja ! Works fine in my 2025.6.0 !

**Comment by shivan** [comment]
Works fine here, too.
Thanks.
